swagger: '2.0'
info:
  description: 耳鸣治疗API
  version: 1.0.0
  title: 耳鸣治疗 API

  contact:
    email: caoxiang@yeah.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

tags:
- name: user
  description: 用户
- name: doctor
  description: 医生
- name: hospital
  description: 医院
- name: range
  description: 频段
- name: setting
  description: 配置

consumes:
  - application/json
produces:
  - application/json

parameters:
  rangeId:
    name: rangeId
    in: path
    description: 频段ID
    type: string
    required: true

paths:
  /user/login:
    get:
      tags:
      - user
      summary: 用户登录
      operationId: userLogin
      description: 用户通过手机号和验证码进行登录，如是第一次自动进行注册，同时完成课程申请
      parameters:
        - name: phone
          in: query
          type: string
          description: 手机号
        - name: code
          in: query
          type: string
          description: 短信验证码
        - name: weixin_code
          in: query
          type: string
          description: 微信Code，用于获取OpenID
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              token:
                type: string
                description: 登录Token
                example: 004fdde865843007d180c43ec240127e
        403:
          description: 登录失败

  /user/protocol:
    get:
      tags:
      - user
      summary: 获取用户协议
      operationId: getUserProtocol
      responses:
        200:
          description: 成功
          schema:
            type: string
            example: 用户协议

  /user:
    post:
      tags:
      - user
      summary: 注册用户
      operationId: userRegister
      description: 注册用户
      parameters:
        - name: phone
          in: query
          type: string
          description: 手机号
          required: true
        - name: code
          in: query
          type: string
          description: 短信验证码
          required: true
        - name: name
          in: query
          type: string
          description: 姓名
          required: true
        - name: hospital
          in: query
          type: integer
          description: 医院ID
          required: true
        - name: doctor
          in: query
          type: integer
          description: 医生ID
      responses:
        200:
          description: 注册成功
        403:
          description: 失败
          schema:
            type: object
            properties:
              code:
                type: string
                description: 状态码
                example: 1
              message:
                type: string
                description: 错误描述
                example: 手机号格式错误

  /range:
    get:
      summary: 获取频段列表
      tags:
        - range
      operationId: getRangeList
      responses:
        200:
          description: 成功
          schema:
            type: array
            items:
              $ref: '#/definitions/Range'

  /user/buy:
    get:
      tags:
        - user
      summary: 购买频段
      operationId: userBuy
      security:
        - APIKeyQueryParam: []
      parameters:
        - name: type
          type: integer
          in: query
          required: true
          description: >
            支付类型:
            1 微信-小程序
      responses:
        200:
          description: 成功

  /hospital:
    get:
      summary: 获取医院列表
      tags:
        - hospital
      operationId: getHospitalList
      responses:
        200:
          description: 成功
          schema:
            type: array
            items:
              $ref: '#/definitions/Hospital'

  /setting:
    get:
      summary: 获取配置
      tags:
        - setting
      operationId: getSettings
      responses:
        200:
          description: 成功
          schema:
            type: array
            items:
              $ref: '#/definitions/Setting'

  /doctor/promote/{doctorId}:
    get:
      summary: 医生推广入口
      tags:
        - doctor
      operationId: doctorPromote
      responses:
        200:
          description: 成功

definitions:
  User:
    description: 用户
    properties:
      id:
        description: 用户ID
        type: string
        example: 6o38l2zzmm4
      name:
        type: string
        description: 名字
        example: 胡漾

  Range:
    description: 频段
    properties:
      id:
        description: 频段ID
        type: integer
        example: 1
      min:
        type: integer
        example: 100
        description: 最小值
      max:
        type: integer
        description: 最大值
        example: 200
      file:
        type: string
        description: 音频
        example: /audio/a.mp3

  Hospital:
    description: 医院
    properties:
      id:
        description: 医院ID
        type: integer
        example: 1
      name:
        type: string
        example: 协和医院
        description: 医院名字

  Setting:
    description: 配置
    properties:
      id:
        description: 配置ID
        type: string
        example: trial_length
      value:
        type: string
        example: {"length":"111","type":"2"}
        description: 配置信息

schemes:
 - https
 
# Added by API Auto Mocking Plugin
host: coach.test.dakashuo.com
basePath: /v1

securityDefinitions:
   # /path?access-token=abcdef12345
   APIKeyQueryParam:
     type: apiKey
     in: query
     name: access-token
     description: 用户鉴权参数